### PR TITLE
Auto-deploy to gh-pages branch using GitHub Actions.

### PR DESCRIPTION
**Pull request by QuLogic**
Currently, this is only done for commits to the `master` branch. If we want to do some scheduled posts, we can have this trigger daily (then posts with a `date` in the future will become visible on some future day).

You can see this [run on my fork](https://github.com/QuLogic/matplotblog/runs/522845340?check_suite_focus=true) when I pushed it to `master`.

### CODE REVIEW

**Comment by davidevaleriani** [comment]
That's great, it makes a lot of sense (and life easier!). Can you make auto-deploy trigger daily and then I will merge?
The main concern is that Github has the most up-to-date version of Hugo (0.67.1) and I encountered some incompatibilities in the past between the theme (aether) and the Hugo's version. So, we just need to be extra-careful before committing and make sure our local version of Hugo is the same that Github uses.

**Comment by QuLogic** [comment]
I can pin Hugo versions if that helps, do you have a specific version in mind?

**Comment by davidevaleriani** [comment]
I have tested 0.62.2, so maybe pin that for now. Then, from time to time, we'll run thorough check locally to make sure everything works with more recent versions and update the auto-deploy?

**Comment by davidevaleriani** [comment]
Thanks!

**Pull request merged**
