### PR TITLE
Industry blog post by Whites Agency

### PR DESCRIPTION
**Pull request by dkajtoch**
Added new industry blog post from Whites Agency (https://whites.agency/). Please review if everything is right.

### CODE REVIEW

**Review by davidevaleriani — CHANGES_REQUESTED** [review]
- Please use a featured image that has been created with matplotlib.
- While we welcome to receive contributions from companies, Matplotblog is not a place to advertise a company and its products, so all posts should be focused on the use of MPL in the company. Please revise the introduction to your post by significantly reducing the company introduction.
- Minor: there are a few typos in the description ("unstuctured" should be "unstructured", "to increases" should be "to increase")

**Comment by tacaswell** [comment]
The lines between advertisement / self-promotion / self-description and what we are ok with in the blog is not clear to me and is something I think needs careful consideration.

@dkajtoch I am excited about this submission! As it is the first from industry post, please bear with us while we sort out the "rules of the road".

**Comment by efiring** [comment]
I don't know what "SEO" is.  I suspect other readers might have the same problem.

**Comment by dkajtoch** [comment]
Thanks for valuable points here. Ok so I noted that featured image needs to be replaced, SEO needs at least explanation and self promotion needs to be reduced. How about the sections where I describe cases (case 1, case 2)?
I will try to push some changes today.

**Comment by dkajtoch** [comment]
@davidevaleriani @tacaswell @efiring I made changes to the Introduction. Instead of focusing on the company I wrote introduction about SEO (what it is and why data driven) and moved to what we do and our insights. I also changed featuredImage to the one we generated with matplotlib. What do you think?

**Review by davidevaleriani — APPROVED** [review]
Thanks for addressing the comments, I think it is now ready to be published.

**Comment by story645** [comment]
Thanks for the submission @dkajtoch! Is there anybody we should/shouldn't tag on Twitter when promoting the post?

**Comment by dkajtoch** [comment]
@story645 I tag @matplotlib each time I publish something on twitter

**Pull request merged**
