### PR TITLE
new blog post about enumerating graphs

### PR DESCRIPTION
**Pull request by khakhalin**
Please check out this blog post. I failed to install Hugo, so wrote the .md file manually, but I think it should work. I even tried to make a thumbnail! (That's the only part I couldn't really preview, so working blindly here)

### CODE REVIEW

**Comment by khakhalin** [comment]
And if you could mention my twitter (@ampanmdagaba) and maybe my github, when you publish the blog post, it would be awesome! :) For now I only added the twitter handle at the very last sentence, but I recon usually authors show their contacts somewhere in the header :) Thanks!

**Comment by davidevaleriani** [comment]
Great post Arseny, thank you!
I have added your Github and Twitter links to the bottom of the page, similarly to most of the other posts.

**Comment by khakhalin** [comment]
Great, thank you so much! Of course I have a typo in the very first paragraph (it should be "drew", not "draw"), but I guess I should firmly step on the throat of my perfectionism and keep it silent :)

Looks fun! I hope people enjoy it!

**Comment by davidevaleriani** [comment]
Fixed!

**Comment by khakhalin** [comment]
Oh, thanks a ton!! :)

**Pull request merged**
