### PR TITLE
Progress Report for GSoC Phase 1 Second Half

### PR DESCRIPTION
**Pull request by SidharthBansal**
Added GSoC Progress Report for the second half of Phase 1 containing information about the implementations done, decisions taken, and future goals as discussed so far.
There is no relevant image for this post.
Thanks

### CODE REVIEW

**Comment by davidevaleriani** [comment]
Thanks Sidhart, please remove the Zoom link to your meetings :)

**Comment by anntzer** [comment]
Other than removing the zoom link, the rest looks good to me.

**Comment by SidharthBansal** [comment]
Done. Thanks

**Comment by davidevaleriani** [comment]
Perhaps also remove HackMD link, as it contains Zoom link too?

**Comment by SidharthBansal** [comment]
Done. Thanks

**Pull request merged**
